/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExampleTwoIndexImport } from './routes/exampleTwo/index'
import { Route as ExampleOneIndexImport } from './routes/exampleOne/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExampleTwoIndexRoute = ExampleTwoIndexImport.update({
  id: '/exampleTwo/',
  path: '/exampleTwo/',
  getParentRoute: () => rootRoute,
} as any)

const ExampleOneIndexRoute = ExampleOneIndexImport.update({
  id: '/exampleOne/',
  path: '/exampleOne/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/exampleOne/': {
      id: '/exampleOne/'
      path: '/exampleOne'
      fullPath: '/exampleOne'
      preLoaderRoute: typeof ExampleOneIndexImport
      parentRoute: typeof rootRoute
    }
    '/exampleTwo/': {
      id: '/exampleTwo/'
      path: '/exampleTwo'
      fullPath: '/exampleTwo'
      preLoaderRoute: typeof ExampleTwoIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exampleOne': typeof ExampleOneIndexRoute
  '/exampleTwo': typeof ExampleTwoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exampleOne': typeof ExampleOneIndexRoute
  '/exampleTwo': typeof ExampleTwoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/exampleOne/': typeof ExampleOneIndexRoute
  '/exampleTwo/': typeof ExampleTwoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exampleOne' | '/exampleTwo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exampleOne' | '/exampleTwo'
  id: '__root__' | '/' | '/exampleOne/' | '/exampleTwo/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleOneIndexRoute: typeof ExampleOneIndexRoute
  ExampleTwoIndexRoute: typeof ExampleTwoIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleOneIndexRoute: ExampleOneIndexRoute,
  ExampleTwoIndexRoute: ExampleTwoIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/exampleOne/",
        "/exampleTwo/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/exampleOne/": {
      "filePath": "exampleOne/index.tsx"
    },
    "/exampleTwo/": {
      "filePath": "exampleTwo/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
